name: IDX-Keepalive 2-Hour Intervals
on:
  schedule:
    # Beijing time is UTC+8, schedule in UTC
    # Run at 6:00, 8:00, 10:00, 12:00, 14:00, 16:00, 18:00, 20:00, 22:00 (Beijing time)
    - cron: '0 22,23 * * *'
  # Manual trigger option
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Restore latest cookies cache
      id: cache-cookies-restore
      uses: actions/cache/restore@v4
      with:
        path: google_cookies.json
        key: google_cookies-restore-attempt-${{ runner.os }}
        restore-keys: |
          google_cookies-
    
    - name: Check if cache was found
      id: check-cache
      run: |
        if [ -f "google_cookies.json" ]; then
          echo "CACHE_HIT=true" >> $GITHUB_OUTPUT
          echo "Using cached cookies file"
        else
          echo "CACHE_HIT=false" >> $GITHUB_OUTPUT
          echo "No cached cookies found"
        fi
    
    - name: Download Google Cookies
      if: steps.check-cache.outputs.CACHE_HIT != 'true'
      run: |
        curl -s -L "${{ secrets.COOK_URL }}" -o google_cookies.json
        if [ -f google_cookies.json ]; then
          echo "Downloaded google_cookies.json successfully"
        else
          echo "Error: Failed to download google_cookies.json"
          exit 1
        fi
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        
        # Install from requirements.txt if it exists
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install playwright
        fi
    
    - name: Setup Playwright
      id: setup-playwright
      uses: microsoft/playwright-github-action@v1
      
    - name: Run Python Script
      env:
        GOOGLE_PW: ${{ secrets.GOOGLE_PW }}
        APP_URL: ${{ secrets.APP_URL }}
      run: |
        # Run the script
        python main.py
        
    - name: Get current timestamp for cookie cache key
      id: timestamp_generator
      run: echo "CACHE_TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
      
    - name: Save cookies cache with timestamp
      uses: actions/cache/save@v4
      with:
        path: google_cookies.json
        key: google_cookies-${{ steps.timestamp_generator.outputs.CACHE_TIMESTAMP }}
