name: IDX Keepalive
on:
  schedule:
    # Run keepalive every 1 hour
    - cron: '0 * * * *'
  # Manual trigger option for testing
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Restore cookies cache
      id: cache-cookies
      uses: actions/cache/restore@v3
      with:
        path: google_cookies.json
        key: google_cookies-v1
        restore-keys: |
          google_cookies-
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Restore pip cache
      id: cache-pip
      uses: actions/cache/restore@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Restore Playwright cache
      id: cache-playwright
      uses: actions/cache/restore@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.version') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
          
    - name: Create playwright.version file if not exists
      run: |
        if [ ! -f "playwright.version" ]; then
          playwright_version=$(pip show playwright 2>/dev/null | grep Version | cut -d ' ' -f 2 || echo "1.34.0")
          echo "$playwright_version" > playwright.version
        fi
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv
        # Install from requirements.txt if it exists
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          pip install playwright
        fi
        # Only install Playwright browsers if cache doesn't exist
        if [ "${{ steps.cache-playwright.outputs.cache-hit }}" != 'true' ]; then
          echo "Installing Playwright browsers..."
          python -m playwright install firefox
        else
          echo "Using cached Playwright browsers"
        fi
        # Install Xvfb for headful mode in CI environment
        sudo apt-get update && sudo apt-get install -y xvfb
        
    - name: Run idx script
      env:
        # Credentials stored in GitHub Secrets
        GOOGLE_PW: ${{ secrets.GOOGLE_PW }}
        APP_URL: ${{ secrets.APP_URL }}
        # Set display for Xvfb
        DISPLAY: ":99.0"
      run: |
        # Start virtual display server
        Xvfb :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
        # Wait for Xvfb to start
        sleep 3
        # Run the script
        python main.py
        
    - name: Save cookies cache
      uses: actions/cache/save@v3
      with:
        path: google_cookies.json
        key: google_cookies-v1
        
    - name: Save pip cache
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        
    - name: Save Playwright cache
      uses: actions/cache/save@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.version') }}
